# /.pages.yml — Pages CMS

media:
  input: "assets/media"
  output: "/assets/media"

content:
  # ---------------------------
  # JEUX
  # ---------------------------
  - name: games
    label: "Jeux"
    type: collection
    path: "content/games"
    create: true
    format: json
    extension: json
    filename: "{{name | slug}}.json"   # slug auto depuis "name"
    fields:
      - { name: name,  label: "Nom",  type: string }
      - { name: short, label: "Description courte", type: text,   required: false }
      - { name: publisher, label: "Éditeur / Studio", type: string, required: false }
      - name: status
        label: "Statut"
        type: select
        options: { values: [ { label: "Actif", value: "actif" }, { label: "Archivé", value: "archive" } ] }
        required: false
      - { name: cover, label: "Cover (16:9)", type: image, required: false }

  # ---------------------------
  # BUILDS
  # ---------------------------
  - name: builds
    label: "Builds"
    type: collection
    path: "content/builds"
    create: true
    format: json
    extension: json
    filename: "{{title | slug}}.json"  # slug auto depuis "title"
    fields:
      - { name: title, label: "Titre", type: string }
      # Jeu en liste déroulante (alimentation depuis content/games/index.json)
      - name: gameName
        label: "Jeu"
        type: select
        options:
          fetch:
            url: "content/games/index.json"
            results: "items"
            value: "name"      # ou "slug" si présent dans tes items
            label: "{{name}}"  # libellé affiché
      - name: tier
        label: "Tier"
        type: select
        options: { values: ["S","A","B","C"] }
        required: false
      - { name: version, label: "Version", type: string, required: false }
      - { name: summary, label: "Résumé",  type: text,   required: false }

      # Difficulté: texte OU étoiles (1..5). L'UI est bornée; le front borne aussi.
      - name: difficulty
        label: "Difficulté (texte)"
        type: select
        options:
          values:
            - { label: "Facile",    value: "facile" }
            - { label: "Moyen",     value: "moyen" }
            - { label: "Difficile", value: "difficile" }
            - { label: "Expert",    value: "expert" }
        required: false
      - { name: difficultyStars, label: "Difficulté (étoiles 1..5)", type: number, min: 1, max: 5, step: 1, required: false }
      - { name: cost,            label: "Coût (pièces 0..5)",        type: number, min: 0, max: 5, step: 1, required: false }

      - { name: cover,     label: "Cover (16:9)", type: image, required: false }
      - { name: updatedAt, label: "Mise à jour",  type: string, required: false }
      - { name: body,      label: "Corps (HTML/Markdown)", type: text, required: false }

  # ---------------------------
  # GUIDES
  # ---------------------------
  - name: guides
    label: "Guides"
    type: collection
    path: "content/guides"
    create: true
    format: json
    extension: json
    filename: "{{title | slug}}.json"
    fields:
      - { name: title, label: "Titre", type: string }
      # Jeu en dropdown (même source que Builds)
      - name: gameName
        label: "Jeu"
        type: select
        options:
          fetch:
            url: "content/games/index.json"
            results: "items"
            value: "name"
            label: "{{name}}"
      - { name: resource, label: "Ressource",  type: string, required: false }
      - { name: route,    label: "Route / Plan", type: text, required: false }
      - { name: cover,    label: "Cover (16:9)", type: image, required: false }
      - { name: date,     label: "Date", type: string, required: false }
      - { name: body,     label: "Corps (HTML/Markdown)", type: text, required: false }

  # ---------------------------
  # OUTILS
  # ---------------------------
  - name: tools
    label: "Outils"
    type: collection
    path: "content/tools"
    create: true
    format: json
    extension: json
    filename: "{{title | slug}}.json"
    fields:
      - { name: title, label: "Titre", type: string }
      - name: kind
        label: "Type"
        type: select
        options: { values: ["Overlay","Plugin","Site","Autre"] }
        required: false
      - { name: url,   label: "URL",   type: string, required: false }
      - { name: notes, label: "Notes", type: text,   required: false }
      # Jeu en dropdown (même source)
      - name: gameName
        label: "Jeu"
        type: select
        options:
          fetch:
            url: "content/games/index.json"
            results: "items"
            value: "name"
            label: "{{name}}"
      - { name: cover, label: "Cover (16:9)", type: image, required: false }
      - { name: body,  label: "Corps (HTML/Markdown)", type: text, required: false }
