media_folder: "assets/media"
public_folder: "/assets/media"

collections:
  - label: "Jeux"
    name: "games"
    folder: "content/games"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Nom",  name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }

  - label: "Builds"
    name: "builds"
    folder: "content/builds"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Slug",  name: "slug",  widget: "string" }

  - label: "Guides"
    name: "guides"
    folder: "content/guides"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Slug",  name: "slug",  widget: "string" }

  - label: "Outils"
    name: "tools"
    folder: "content/tools"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Slug",  name: "slug",  widget: "string" }
