# Pages CMS (.pages.yml)

media:
  input: "assets/media"
  output: "/assets/media"

content:
  # ---------------------------
  # JEUX
  # ---------------------------
  - name: games
    label: "Jeux"
    type: collection
    path: "content/games"
    create: true
    format: json
    extension: json
    filename: "{{slug}}.json"
    fields:
      - { name: name,  label: "Nom",  type: string }
      - { name: slug,  label: "Slug", type: string }
      - name: status
        label: "Statut"
        type: select
        options:
          values:
            - { label: "Actif",   value: "actif" }
            - { label: "Archivé", value: "archive" }
        required: false
      - { name: short,     label: "Description courte", type: text,   required: false }
      - { name: publisher, label: "Éditeur / Studio",   type: string, required: false }
      - name: cover
        label: "Cover (16:9)"
        type: image
        required: false

  # ---------------------------
  # BUILDS
  # ---------------------------
  - name: builds
    label: "Builds"
    type: collection
    path: "content/builds"
    create: true
    format: json
    extension: json
    filename: "{{slug}}.json"
    fields:
      - { name: title, label: "Titre", type: string }
      - { name: slug,  label: "Slug",  type: string }
      - { name: gameName, label: "Nom du jeu", type: string, required: false }
      - name: tier
        label: "Tier"
        type: select
        options:
          values: ["S","A","B","C"]
        required: false
      - { name: version, label: "Version", type: string, required: false }
      - { name: summary, label: "Résumé",  type: text,   required: false }
      - name: difficulty
        label: "Difficulté (texte)"
        type: select
        options:
          values:
            - { label: "Facile",    value: "facile" }
            - { label: "Moyen",     value: "moyen" }
            - { label: "Difficile", value: "difficile" }
            - { label: "Expert",    value: "expert" }
        required: false
      - { name: difficultyStars, label: "Difficulté (étoiles 1..5)", type: number, min: 1, max: 5, required: false }
      - { name: cost,            label: "Coût (pièces 0..5)",        type: number, min: 0, max: 5, required: false }
      - name: cover
        label: "Cover (16:9)"
        type: image
        required: false
      - { name: updatedAt, label: "Mise à jour", type: string, required: false }
      - { name: body,      label: "Corps (HTML/Markdown)", type: text, required: false }

  # ---------------------------
  # GUIDES
  # ---------------------------
  - name: guides
    label: "Guides"
    type: collection
    path: "content/guides"
    create: true
    format: json
    extension: json
    filename: "{{slug}}.json"
    fields:
      - { name: title, label: "Titre", type: string }
      - { name: slug,  label: "Slug",  type: string }
      - { name: gameName, label: "Nom du jeu", type: string, required: false }
      - { name: resource, label: "Ressource",  type: string, required: false }
      - { name: route,    label: "Route / Plan", type: text, required: false }
      - name: tips
        label: "Tips"
        type: list
        field: { name: tip, label: "Tip", type: string }
        required: false
        default: []
      - name: cover
        label: "Cover (16:9)"
        type: image
        required: false
      - { name: date, label: "Date", type: string, required: false }
      - { name: body, label: "Corps (HTML/Markdown)", type: text, required: false }

  # ---------------------------
  # OUTILS
  # ---------------------------
  - name: tools
    label: "Outils"
    type: collection
    path: "content/tools"
    create: true
    format: json
    extension: json
    filename: "{{slug}}.json"
    fields:
      - { name: title, label: "Titre", type: string }
      - { name: slug,  label: "Slug",  type: string, required: false }
      - name: kind
        label: "Type"
        type: select
        options:
          values: ["Overlay","Plugin","Site","Autre"]
        required: false
      - { name: url,   label: "URL",   type: string, required: false }
      - { name: notes, label: "Notes", type: text,   required: false }
      - { name: gameName, label: "Nom du jeu", type: string, required: false }
      - name: cover
        label: "Cover (16:9)"
        type: image
        required: false
      - { name: body, label: "Corps (HTML/Markdown)", type: text, required: false }
