media:
  input: "assets/media"
  output: "/assets/media"

collections:
  - name: "games"
    label: "Jeux"
    type: "directory"
    path: "content/games"
    create: true
    format: "json"
    extension: "json"
    fields:
      - { name: "name", label: "Nom",  type: "string" }
      - { name: "slug", label: "Slug", type: "string" }

  - name: "builds"
    label: "Builds"
    type: "directory"
    path: "content/builds"
    create: true
    format: "json"
    extension: "json"
    fields:
      - { name: "title", label: "Titre", type: "string" }
      - { name: "slug",  label: "Slug",  type: "string" }

  - name: "guides"
    label: "Guides"
    type: "directory"
    path: "content/guides"
    create: true
    format: "json"
    extension: "json"
    fields:
      - { name: "title", label: "Titre", type: "string" }
      - { name: "slug",  label: "Slug",  type: "string" }

  - name: "tools"
    label: "Outils"
    type: "directory"
    path: "content/tools"
    create: true
    format: "json"
    extension: "json"
    fields:
      - { name: "title", label: "Titre", type: "string" }
      - { name: "slug",  label: "Slug",  type: "string" }
