# /.pages.yml — version compacte qui ré-affiche les 4 collections dans la barre latérale

media:
  input: "assets/media"
  output: "/assets/media"

collections:
  games:
    label: "Jeux"
    type: "directory"
    path: "content/games"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { name: "name",  label: "Nom",  type: "string" }
      - { name: "slug",  label: "Slug", type: "string" }

  builds:
    label: "Builds"
    type: "directory"
    path: "content/builds"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Titre", type: "string" }
      - { name: "slug",  label: "Slug",  type: "string" }

  guides:
    label: "Guides"
    type: "directory"
    path: "content/guides"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Titre", type: "string" }
      - { name: "slug",  label: "Slug",  type: "string" }

  tools:
    label: "Outils"
    type: "directory"
    path: "content/tools"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Titre", type: "string" }
      - { name: "slug",  label: "Slug",  type: "string" }
