media_folder: "assets/media"
public_folder: "/assets/media"

collections:
  - label: "Jeux"
    name: "games"
    files:
      - label: "League of Legends"
        name: "league-of-legends"
        file: "content/games/league-of-legends.json"
        format: "json"
        fields:
          - { label: "Nom",  name: "name", widget: "string" }
          - { label: "Slug", name: "slug", widget: "string" }

      - label: "Counter-Strike 2"
        name: "counter-strike-2"
        file: "content/games/counter-strike-2.json"
        format: "json"
        fields:
          - { label: "Nom",  name: "name", widget: "string" }
          - { label: "Slug", name: "slug", widget: "string" }

  - label: "Builds"
    name: "builds"
    files:
      - label: "Aatrox Top – Sustained Carry"
        name: "aatrox-top-sustained-carry"
        file: "content/builds/aatrox-top-sustained-carry.json"
        format: "json"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Slug",  name: "slug",  widget: "string" }
